/**
 * Defines the graph editor model.
 * <p>
 * Classes are auto generated by Eclipse EMF, see <code>graph.ecore</code> and
 * <code>graph.genmodel</code>
 */
module org.cetc.dataproc.model
{
    requires transitive org.eclipse.emf.ecore;
    requires org.eclipse.emf.common;

    exports sy.grapheditor.model;
    exports sy.grapheditor.model.impl;
}